# Setting Up the Environment

## Importing Libraries:

- **langchain-google-genai**: A LangChain integration that enables seamless interaction with Google's AI models, such as Gemini-Pro, for advanced language processing and AI workflows.  
- **langchain.prompts import PromptTemplate**: A utility in LangChain for creating dynamic, reusable text prompts with placeholders for structured AI interactions.  
- **requests**: A popular library for making HTTP requests in Python.  
- **json**: Used for parsing JSON data, which is common in API responses.  
- **from google.colab**: Used to securely store and retrieve user-specific data in Google Colab.
- **llumo** :To evaluate the outputs of the model

In [2]:
%pip install langchain
%pip install langchain langchain-google-genai
%pip install llumo
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.prompts import PromptTemplate
from google.colab import userdata

# Secure API key handling

In [4]:
LLUMOAI_KEY = userdata.get("LLUMOAI_API_KEY")  # Ensure this is set in the environment(Visit https://app.llumo.ai/ to get your own Api key)
GOOGLE_KEY = "Enter Your Google Api Key "

# Ensure API key is available
if not GOOGLE_KEY:
    raise ValueError("Missing Google AI API key. Set GOOGLE_API_KEY as an environment variable.")

# Initialize Google Gemini-Pro model
chatModel = ChatGoogleGenerativeAI(model="gemini-2.0-flash", google_api_key=GOOGLE_KEY)

# Defining Prompt

In [5]:
# Defining the Prompt
promptTemplate = PromptTemplate.from_template("Explain {topic} in a simple and easy-to-understand way.")

# Creating Chain

In [6]:
# Create a chain
chain = promptTemplate | chatModel

# Getting Respone

In [7]:
# Run the chain with a topic
topic = "quantum physics"
response = chain.invoke({"topic": topic})

In [8]:
output=response.content

In [11]:
input=promptTemplate.template
output=output
query=topic

In [12]:
data={"topic":[query],"output":[output],}
import pandas as pd
df=pd.DataFrame(data)
df

             topic                                             output
0  quantum physics  Okay, let's try to understand quantum physics ...

# Evaluating Responses with Llumo

##Evaluate the Gemini Response:
-We evaluate the response generated by the Google Gemini Model, using the Llumo evaluation Sdk.</br>

In [13]:
from llumo import  LlumoClient
client = LlumoClient(api_key="Enter Your Llumo Ai Api")
res = client.evaluate(df,evals = ["Response Correctness"],prompt_template="Explain {{topic}} in a simple and easy-to-understand way.")

======= Running evaluation for: Response Correctness =======

In [14]:
res

,topic,output,Response Correctness
0,quantum physics,"Okay, let's try to understand quantum physics ...",99