##Setting up the environment
###Importing libraries:

* os: This module provides a way to use operating system dependent functionality, like reading environment variables.
* OpenAI: This is the official OpenAI Python client, used to interact with OpenAI's API.
* requests: A popular library for making HTTP requests in Python.
* json: Used for parsing JSON data, which is common in API responses.
* logging: Provides a flexible framework for generating log messages in Python.
* getpass: Allows secure password prompts where the input is not displayed on the screen.
* llumo : To evaluate the outputs of the model

###Setting up logging:

* We use `logging.basicConfig()` to configure the logging system. The `level=logging.INFO` argument sets the threshold for logging messages to INFO level and above.
* We create a logger object named logger that we'll use throughout our script to log important information and errors.



This setup ensures we have all necessary tools to interact with APIs, handle data, and track any issues that might occur during execution.

In [1]:
!pip install openai
!pip install llumo
import os
from openai import OpenAI
import requests
import json
import logging
from getpass import getpass

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

print("Libraries imported and logging set up successfully.")

Requirement already satisfied: openai in /usr/local/lib/python3.11/dist-packages (1.75.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from openai) (4.9.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.9.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from openai) (2.11.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.11/dist-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.11/dist-packages (from openai) (4.13.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.5.0->openai) (3.10)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai) (2025.1.31)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.8)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.14.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.1 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (2.33.1)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.0)
Collecting llumo
  Downloading llumo-0.1.7-py3-none-any.whl.metadata (721 bytes)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from llumo) (2.32.3)
Requirement already satisfied: websocket-client>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from llumo) (1.8.0)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from llumo) (2.2.2)
Requirement already satisfied: numpy>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from llumo) (2.0.2)
Collecting python-socketio==5.13.0 (from python-socketio[client]==5.13.0->llumo)
  Downloading python_socketio-5.13.0-py3-none-any.whl.metadata (3.2 kB)
Collecting python-dotenv==1.1.0 (from llumo)
  Downloading python_dotenv-1.1.0-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: openai==1.75.0 in /usr/local/lib/python3.11/dist-packages (from llumo) (1.75.0)
Requirement already satisfied: google-generativeai==0.8.5 in /usr/local/lib/python3.11/dist-packages (from llumo) (0.8.5)
Requirement already satisfied: google-ai-generativelanguage==0.6.15 in /usr/local/lib/python3.11/dist-packages (from google-generativeai==0.8.5->llumo) (0.6.15)
Requirement already satisfied: google-api-core in /usr/local/lib/python3.11/dist-packages (from google-generativeai==0.8.5->llumo) (2.24.2)
Requirement already satisfied: google-api-python-client in /usr/local/lib/python3.11/dist-packages (from google-generativeai==0.8.5->llumo) (2.164.0)
Requirement already satisfied: google-auth>=2.15.0 in /usr/local/lib/python3.11/dist-packages (from google-generativeai==0.8.5->llumo) (2.38.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.11/dist-packages (from google-generativeai==0.8.5->llumo) (5.29.4)
Requirement already satisfied: pydantic in /usr/local/lib/python3.11/dist-packages (from google-generativeai==0.8.5->llumo) (2.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from google-generativeai==0.8.5->llumo) (4.67.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.11/dist-packages (from google-generativeai==0.8.5->llumo) (4.13.2)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from openai==1.75.0->llumo) (4.9.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from openai==1.75.0->llumo) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from openai==1.75.0->llumo) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from openai==1.75.0->llumo) (0.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from openai==1.75.0->llumo) (1.3.1)
Collecting bidict>=0.21.0 (from python-socketio==5.13.0->python-socketio[client]==5.13.0->llumo)
  Downloading bidict-0.23.1-py3-none-any.whl.metadata (8.7 kB)
Collecting python-engineio>=4.11.0 (from python-socketio==5.13.0->python-socketio[client]==5.13.0->llumo)
  Downloading python_engineio-4.12.0-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /usr/local/lib/python3.11/dist-packages (from google-ai-generativelanguage==0.6.15->google-generativeai==0.8.5->llumo) (1.26.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->llumo) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->llumo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->llumo) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->llumo) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->llumo) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->llumo) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->llumo) (2025.1.31)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core->google-generativeai==0.8.5->llumo) (1.70.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from google-auth>=2.15.0->google-generativeai==0.8.5->llumo) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from google-auth>=2.15.0->google-generativeai==0.8.5->llumo) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from google-auth>=2.15.0->google-generativeai==0.8.5->llumo) (4.9.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai==1.75.0->llumo) (1.0.8)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai==1.75.0->llumo) (0.14.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic->google-generativeai==0.8.5->llumo) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.1 in /usr/local/lib/python3.11/dist-packages (from pydantic->google-generativeai==0.8.5->llumo) (2.33.1)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic->google-generativeai==0.8.5->llumo) (0.4.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->llumo) (1.17.0)
Collecting simple-websocket>=0.10.0 (from python-engineio>=4.11.0->python-socketio==5.13.0->python-socketio[client]==5.13.0->llumo)
  Downloading simple_websocket-1.1.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: httplib2<1.dev0,>=0.19.0 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client->google-generativeai==0.8.5->llumo) (0.22.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client->google-generativeai==0.8.5->llumo) (0.2.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client->google-generativeai==0.8.5->llumo) (4.1.1)
Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai==0.8.5->llumo) (1.71.0)
Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai==0.8.5->llumo) (1.71.0)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /usr/local/lib/python3.11/dist-packages (from httplib2<1.dev0,>=0.19.0->google-api-python-client->google-generativeai==0.8.5->llumo) (3.2.3)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.11/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai==0.8.5->llumo) (0.6.1)
Collecting wsproto (from simple-websocket>=0.10.0->python-engineio>=4.11.0->python-socketio==5.13.0->python-socketio[client]==5.13.0->llumo)
  Downloading wsproto-1.2.0-py3-none-any.whl.metadata (5.6 kB)
Downloading llumo-0.1.7-py3-none-any.whl (13 kB)
Downloading python_dotenv-1.1.0-py3-none-any.whl (20 kB)
Downloading python_socketio-5.13.0-py3-none-any.whl (77 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.8/77.8 kB 2.6 MB/s eta 0:00:00
Downloading bidict-0.23.1-py3-none-any.whl (32 kB)
Downloading python_engineio-4.12.0-py3-none-any.whl (59 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.3/59.3 kB 2.7 MB/s eta 0:00:00
Downloading simple_websocket-1.1.0-py3-none-any.whl (13 kB)
Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Installing collected packages: wsproto, python-dotenv, bidict, simple-websocket, python-engineio, python-socketio, llumo
Successfully installed bidict-0.23.1 llumo-0.1.7 python-dotenv-1.1.0 python-engineio-4.12.0 python-socketio-5.13.0 simple-websocket-1.1.0 wsproto-1.2.0
Libraries imported and logging set up successfully.

##Secure API key handling
###Secure API key input:

* We use `getpass()` to prompt the user for their API keys. This function hides the input, making it more secure than using regular input().
* This approach is safer than hardcoding API keys in your script, which could accidentally be shared or exposed.


###Setting environment variables:

* We use `os.environ` to set environment variables for both API keys.
* Environment variables are a secure way to store sensitive information, as they're not part of your code and are only accessible within the current process.


###Initializing the OpenAI client:

* We create an instance of the OpenAI client using the API key we just set.
* Using `os.getenv("OPENAI_API_KEY")` retrieves the API key from the environment variables.



This method ensures that your API keys are handled securely and are readily available for use in your script.

In [2]:
# Cell 2: Secure API key handling

# Securely input API keys
openai_api_key = getpass("Enter your OpenAI API key: ")
llumo_api_key = getpass("Enter your Llumo API key: ")

# Set environment variables
os.environ['OPENAI_API_KEY'] = openai_api_key
os.environ['LLUMO_API_KEY'] = llumo_api_key

del openai_api_key
del llumo_api_key


# Initialize OpenAI client
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

print("API keys securely set and OpenAI client initialized.")

Enter your OpenAI API key: ··········
Enter your Llumo API key: ··········
API keys securely set and OpenAI client initialized.

# Getting Respone from OpenAI

### Define Example Prompt:
* We define an example prompt to be used for testing without compression.


This segment of code demonstrates how to define an example prompt and test the response generation without applying any compression, using the OpenAI API. It includes the prompt definition, API request, and response extraction steps.

In [4]:
# Cell 4: Define example prompt and test without compression

# Example prompt
prompt = """
Contest:{{Context}},
Query:{{query}}
Instructions:You are a helpful and informative chatbot designed to answer questions about Flexicab, a SaaS platform for Rickshaw drivers and owners. Use the provided context to answer the user's query in a comprehensive and engaging manner. **Response Format:*** Begin your response with a clear and concise answer to the user's question.* Provide additional details and explanations to support your answer, drawing from the provided context.* Use bullet points or numbered lists to organize information and make it easier to read.* If applicable, include specific examples or scenarios to illustrate your points.* End your response with a friendly and helpful tone, encouraging further interaction.**
"""
Context="Flexicab: The Smart Rickshaw Management PlatformFlexicab is a revolutionary SaaS platform designed specifically for Rickshaw drivers and owners in bustling urban environments. It addresses the unique challenges faced by this vital mode of transportation, empowering them with modern tools to optimize their operations and increase their earnings.**Key Features:*** **Route Optimization:** Flexicab leverages real-time traffic data and historical ride patterns to suggest the most efficient routes for each trip, minimizing travel time and fuel consumption. This feature helps drivers maximize their earnings by completing more rides within a given timeframe.* **Fare Calculation & Management:** Flexicab automatically calculates fares based on distance, time, and other factors, ensuring transparency and accuracy for both drivers and passengers. It also integrates with popular payment gateways, allowing for seamless digital transactions and reducing the risk of cash handling.* **Customer Management:** Flexicab provides a platform for drivers to manage their customer base, track ride history, and build loyalty through personalized offers and promotions. This helps drivers attract repeat customers and increase their overall revenue.* **Fleet Management:** For Rickshaw owners with multiple vehicles, Flexicab offers a comprehensive fleet management system. This includes vehicle tracking, maintenance scheduling, driver performance monitoring, and real-time communication tools to ensure efficient operations and safety.* **Data Analytics & Insights:** Flexicab provides valuable insights into driver performance, customer behavior, and market trends. This data can be used to optimize pricing strategies, identify high-demand areas, and make informed business decisions.**Benefits:*** **Increased Earnings:** By optimizing routes, managing fares effectively, and attracting more customers, Flexicab helps drivers significantly increase their earnings.* **Improved Efficiency:** Flexicab streamlines operations, reducing wasted time and effort, allowing drivers to focus on providing excellent service.* **Enhanced Safety:** The platform's features, such as vehicle tracking and driver performance monitoring, contribute to a safer environment for both drivers and passengers.* **Digital Transformation:** Flexicab empowers Rickshaw drivers and owners to embrace digital technology, making their businesses more modern and competitive.**Target Audience:*** Rickshaw drivers* Rickshaw owners* Transportation companies operating Rickshaws* City governments and transportation authorities looking to improve urban mobility and support sustainable transportation options.**Flexicab is more than just a platform; it's a comprehensive solution that empowers Rickshaw drivers and owners to thrive in the modern urban landscape."
Query= "How does Flexicab help Rickshaw drivers increase their earnings?"

prompt = prompt.replace("{{Context}}", Context).replace("{{query}}", Query)



response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": prompt}
    ]
)
openai_output=response.choices[0].message.content
print(openai_output)
print(f"Tokens used: {response.usage.total_tokens}\n")

**How does Flexicab help Rickshaw drivers increase their earnings?**

- **Route Optimization:** Flexicab utilizes real-time traffic data and historical ride patterns to suggest the most efficient routes for each trip. By minimizing travel time and fuel consumption, drivers can complete more rides within a given timeframe, thus increasing their earnings.

- **Fare Calculation & Management:** The platform automatically calculates fares based on distance, time, and other factors, ensuring transparency and accuracy for both drivers and passengers. This feature helps drivers earn fair compensation for their services and eliminates any confusion or disputes over pricing.

- **Customer Management:** Flexicab provides a platform for drivers to manage their customer base, track ride history, and offer personalized promotions to build customer loyalty. By attracting repeat customers and increasing ride frequency, drivers can boost their overall revenue.

- **Data Analytics & Insights:** By providing valuable insights into driver performance, customer behavior, and market trends, Flexicab enables drivers to optimize pricing strategies, identify high-demand areas, and make informed business decisions. This data-driven approach can lead to increased earnings by targeting lucrative opportunities in the market.

By leveraging these key features, Flexicab empowers Rickshaw drivers to maximize their earnings, optimize their operations, and thrive in the modern urban landscape. If you have any more questions or need further assistance, feel free to ask!
Tokens used: 922

In [5]:
output=openai_output

In [8]:
data={"Query":[Query],"Context":[Context],"output":[output]}
import pandas as pd
df=pd.DataFrame(data)
df

,Query,Context,output
0,How does Flexicab help Rickshaw drivers increa...,Flexicab: The Smart Rickshaw Management Platfo...,**How does Flexicab help Rickshaw drivers incr...

# Evaluating Responses with Llumo

### Evaluate the OpenAI Response:
* We evaluate the response generated by the OpenAI API using the Llumo evaluation Sdk.

In [9]:
from llumo import  LlumoClient
client = LlumoClient(api_key="Enter Your Llumo Api Key")
res = client.evaluate(df,evals = ["Response Correctness"],prompt_template="Give the answer to Query:{{Query}} using the given Context:{{Context}}")

======= Running evaluation for: Response Correctness =======

In [10]:
res

,Query,Context,output,Response Correctness
0,How does Flexicab help Rickshaw drivers increa...,Flexicab: The Smart Rickshaw Management Platfo...,**How does Flexicab help Rickshaw drivers incr...,99